# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontened_jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisUi(object):
    def setupUi(self, jarvisUi):
        jarvisUi.setObjectName("jarvisUi")
        jarvisUi.resize(908, 575)
        self.buttonBox = QtWidgets.QDialogButtonBox(jarvisUi)
        self.buttonBox.setGeometry(QtCore.QRect(150, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(jarvisUi)
        self.label.setGeometry(QtCore.QRect(-210, 0, 1201, 581))
        self.label.setStyleSheet("background:transparent")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/iron_jarvis.gif"))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(jarvisUi)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 520, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(jarvisUi)
        self.pushButton.setGeometry(QtCore.QRect(720, 520, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(jarvisUi)
        self.textBrowser.setGeometry(QtCore.QRect(490, 10, 211, 31))
        self.textBrowser.setStyleSheet("background:transparent\n"
"border-radius:none"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(jarvisUi)
        self.textBrowser_2.setGeometry(QtCore.QRect(700, 10, 201, 31))
        self.textBrowser_2.setStyleSheet("background:transparent\n"
"border-radius:none\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(jarvisUi)
        self.label_2.setGeometry(QtCore.QRect(-150, 250, 441, 321))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Downloads/logo_iron.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(jarvisUi)
        self.label_3.setGeometry(QtCore.QRect(370, 50, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(jarvisUi)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 451, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Downloads/initiating system.gif"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(jarvisUi)
        self.buttonBox.accepted.connect(jarvisUi.accept) # type: ignore
        self.buttonBox.rejected.connect(jarvisUi.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(jarvisUi)

    def retranslateUi(self, jarvisUi):
        _translate = QtCore.QCoreApplication.translate
        jarvisUi.setWindowTitle(_translate("jarvisUi", "jarvisUi"))
        self.pushButton_2.setText(_translate("jarvisUi", "Exit"))
        self.pushButton.setText(_translate("jarvisUi", "Run"))
        self.label_3.setText(_translate("jarvisUi", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisUi = QtWidgets.QDialog()
    ui = Ui_jarvisUi()
    ui.setupUi(jarvisUi)
    jarvisUi.show()
    sys.exit(app.exec_())
